apiVersion: v1
kind: Pod
metadata:
  name: slave-fts5l-bbg62
spec:
  containers:
  - name: ez-docker-helm-build
    image: ezezeasy/ez-docker-helm-build:1.41
    imagePullPolicy: Always
    securityContext:
      privileged: true
