apiVersion: apps/v1
kind: Deployment
metadata:
  name: linapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linapp
  template:
    metadata:
      labels:
        app: linapp
    spec:
      containers:
        - name: linapp
          image: linschneider/finalproject:latest
          ports:
            - containerPort: 9101
