apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      containers:
        - name: argocd-server
          image: argoproj/argocd:v2.1.1  # Adjust the version as needed
          ports:
            - containerPort: 8000
