apiVersion: v1
kind: Service
metadata:
  name: argocd-custom-service
  namespace: argocd
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app.kubernetes.io/name: argocd-server
